collections:
  - name: azure.azcollection
  - name: community.windows
  - name: google.cloud
  - name: ansible.windows
  - name: community.azure
  - name: chocolatey.chocolatey
  - name: community.windows.win_dns_zone
  - name: community.windows.win_dns_record