---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: westus2

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ rg_name }}"
    name: myVnet
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ rg_name }}"
    name: mySubnet
    address_prefix: "10.0.1.0/24"
    virtual_network: myVnet

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ rg_name }}"
    allocation_method: Static
    name: myPublicIP
  register: output_ip_address

- name: Public IP of VM
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."

- name: Create Network Security Group that allows WinRM
  azure_rm_securitygroup:
    resource_group: "{{ rg_name }}"
    name: myNetworkSecurityGroup
    #state: "{{ state }}"
    rules:
      - name: WinRM
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1001
        direction: Inbound
        source_address_prefix: "{{ source_public_ip }}"

- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: "{{ rg_group }}"
    vault_name: "{{ keyvault_name }}"
    vault_tenant: "{{ azure_tenant }}"
    location: "{{ location }}"
    enabled_for_disk_encryption: yes
    enabled_for_deployment: yes
    enable_soft_delete: yes
    enable_purge_protection: yes
    sku:
      name: standard
      family: A
    access_policies:
      - object_id: "{{ object_id }}"
        keys:
          - get
          - list
          - update
          - create
          - import
          - delete
          - recover
          - backup
          - restore
          - purge
        secrets:
          - get
          - list
          - set
          - delete
          - recover
          - backup
          - restore
          - purge
        certificates:
          - list
          - delete
          - create
          - import
          - update
          - managecontacts
          - getissuers
          - listissuers
          - setissuers
          - deleteissuers
          - manageissuers
          - recover
          - purge

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ rg_name }}"
    name: myNIC
    virtual_network: myVnet
    subnet: mySubnet
    security_group: myNetworkSecurityGroup
    ip_configurations:
      - public_ip_name: myPublicIP
        name: nicMyVM-IP
        primary: True

- name: create Azure storage account
  azure_rm_storageaccount:
    name: myvm0985645
    resource_group: "{{ rg_name }}"
    account_type: Standard_LRS

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    name: myVM
    vm_size: Standard_DS2_v2
    admin_username: azureadmin
    admin_password: "{{ admin_password }}"
    network_interfaces: myNIC
    managed_disk_type: Standard_LRS
    vm_identity: SystemAssigned
    os_type: Windows
    state: "{{ state }}"
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: "2022-datacenter-core-g2"
      version: latest
    storage_account_name: myvm0985645
    virtual_network_name: myVnet

- name: create Azure vm extension to enable HTTPS WinRM listener
  when: state == "present"
  azure_rm_virtualmachineextension:
    name: winrm-extension
    resource_group: "{{ rg_name }}"
    virtual_machine_name: myVM
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: "1.9"
    settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
    auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  when: state == "present"
  wait_for:
    port: 5986
    host: "{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}"
    timeout: 600

# - name: Encrypt VM with Azure Disk Encryption
#   when: state == "present"
#   shell: az vm encryption enable --resource-group {{ rg_name }} --name myVM --disk-encryption-keyvault {{ keyvault_name }}
#   register: encryption_output

# - name: Output Encryption Results
#   debug:
#     msg: encryption_output