---
- hosts: localhost
  connection: local

  tasks:
  - name: Get Key Vault by name
    keyvault: "{{ vaultkv_secret }}"
    set_fact: secretValue

  - name: Output key vault secret
    debug:
      msg: "{{ secretValue }}"
