---
- hosts: localhost
  connection: local

  tasks:
  - name: Get Key Vault by name
    secretValue: "{{ vaultkv_secret }}"
    register: secretValue

  - name: Output key vault secret
    debug:
      msg: "{{ secretValue }}"
