---
- hosts: localhost
  connection: local

  tasks:
  - name: Get Key Vault by name
    set_fact: 
      secretValue: "{{ vaultkv_secret }}" 

  - name: Output key vault secret
    debug:
      msg: "{{ secretValue }}"
