---
- hosts: localhost
  connection: local

  tasks:
  - name: Create a secret
    azure_rm_keyvaultsecret:
      secret_name: testsecret
      secret_value: My_Pass_Sec_From_AWX_!2#4%$
      keyvault_uri: https://stormesvault.vault.azure.net/
      tags:
          testing: testing
          delete: never
