---
- hosts: localhost
  connection: local

  tasks:
  - name: Create a virtual network
  azure_rm_virtualnetwork:
    resource_group: testsecret
    name: myVirtualNetwork
    address_prefixes_cidr:
        - "10.1.0.0/16"
        - "172.100.0.0/16"
    dns_servers:
        - "127.0.0.1"
        - "127.0.0.2"
    tags:
        testing: testing
        delete: on-exit
