---
- hosts: localhost
  connection: local

  tasks:
  - name: Create Public Azure ACI 
    azure_rm_containerinstance:
      resource_group: "{{ rg_name }}"
      name: "{{ container_group }}"
      os_type: "{{ os_type }}"
      ip_address: public
      dns_name_label: "{{ dnsnamelabel }}"
      containers:
        - name: "{{ container_name1 }}"
          image: "{{ image_name1 }}"
          memory: "{{ memory_amount1 }}"
          cpu: "{{ cpu_count1 }}"
          volume_mounts:
            - name: "{{ filesharevolume }}"
              mount_path: "{{ mount_path }}"
          ports:
            - "{{ port1 }}"
        - name: "{{ container_name2 }}"
          image: "{{ image_name2 }}"
          memory: "{{ memory_amount2 }}"
          cpu: "{{ cpu_count2 }}"
          volume_mounts:
            - name: "{{ filesharevolume }}"
              mount_path: "{{ mount_path }}"
          ports:
            - "{{ port2 }}"
      volumes:
        - name: "{{ filesharevolume }}"
          azure_file:
            storage_account_name: "{{ mystorageaccount }}"
            share_name: "{{ file_share_name }}"
            storage_account_key: "{{ storageaccountkey }}"
  
  - name: Get specific Container Instance facts
    azure_rm_containerinstance_info:
      resource_group: "{{ rg_name }}"
      name: "{{ container_group }}"
