---
- hosts: localhost
  connection: local

  tasks:
  - name: Create a secret
    azure_rm_keyvaultsecret:
      secret_name: testsecret
      secret_value: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      keyvault_uri: https://stormesvault.vault.azure.net/
      tags:
          testing: testing
          delete: never
