---
- hosts: localhost
  connection: local

  tasks:
  - name: Create a Resource Group
    azure_rm_resourcegroup:
      name: testsecret
      location: westus
      tags:
          testing: testing
          delete: never
