- name: Delete a GCP instance
  hosts: localhost
  vars:
     gcp_project: o365-cloud-security
     gcp_cred_kind: serviceaccount
  tasks:
    - name: Delete a  VPC network
      gcp_compute_network:
        name: "{{ network_instance }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: absent
      register: network

    - name: Delete IPv4 public IP Address
      gcp_compute_address:
        name: "{{ address_instance }}"
        region: us-west1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: absent
      register: address
