- name: Delete a GCP instance
  hosts: localhost
  vars:
     gcp_project: o365-cloud-security
     gcp_cred_kind: serviceaccount
  tasks:
    - name: Delete a  VPC network
      gcp_compute_network:
        name: "{{ network_instance }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: absent
      register: network
