- name: Create GCP VPC
  hosts: localhost
  vars:
    gcp_project: o365-cloud-security
    gcp_cred_kind: serviceaccount
  tasks:
    - name: Create VPC
      gcp_compute_network:
        name: test-vpc
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: network
