- name: Create a GCP instance
  hosts: localhost
  tasks:
  - name: Create a GCP instance
    gcp_resourcemanager_project:
      id: brainstormestest-{{ 1000000 | random }}
      auth_kind: serviceaccount
      parent:
        type: organization
        id: "{{ org_id }}"
      state: present