---
- name: Manage Linux Resource Creation
  hosts: localhost
  connection: local
  gather_facts: true
  setup:
    gather_subset:
      - 'all'
  collections:
    - azure.azcollection

  roles:
      - Common