---
- name: Manage Linux Resource Creation Orchestration
  hosts: localhost
  connection: local
  gather_facts: true
  collections:
    - azure.azcollection
   
  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - include: Common/tasks/main.yml
      tags: [Common, all]

  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."