---
# KeyVault Retrieval
# Add variables where no good common place exists
- debug:
    msg: "Common layer for set up of actions to be used in the role."

- name: Example from an Ansible Playbook
  win_ping:

- name: Ensure primary zone is present
  community.windows.win_dns_zone:
    name: "{{ dns_zone_primary }}"
    type: primary
    replication: domain
    state: Present
  tags: CreateZone

- name: Create static record
  win_dns_record:
    name: '{{ A_record_name }}'
    type: '{{ record_type }}'
    value: '{{ ip_address }}'
    state: 'Present'
    zone: "brainstormes.org"
  tags: CreateARecord