---
- name: Ensure primary zone is present
  ansible.community.win_dns_zone:
    name: '{{ dns_zone_primary }}'
    type: primary
    replication: domain
    state: present
  tags: CreateDNSZone

- name: Create static record
  ansible.community.win_dns_record:
    name: '{{ A_record_name }}'
    type: '{{ record_type }}'
    value: '{{ ip_address }}'
    state: 'Present'
    zone: "brainstormes.org"
  tags: CreateARecord