---
# KeyVault Retrieval
# Add variables where no good common place exists
- debug:
    msg: "Common layer for set up of actions to be used in the role."

- name: Example from an Ansible Playbook
  win_ping:

- name: Remove static record
  win_dns_record:
    name: "lab2"
    type: "A"
    value: '192.168.1.5'
    state: Present
    zone: "brainstormes.org"