---
- name: Install PS Modules
  win_psmodule:
    name: '{{ item }}'
    state: Present
  with_items:
  - xWebAdministration
  - CISDSC
  - cChoco

- name: Enable firewall for Domain, Public and Private profiles
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
  tags: enable_firewall
  
- name: Firewall rule to allow SMTP on TCP port 25
  win_firewall_rule:
    name: SMTP
    localport: 25
    action: allow
    direction: in
    protocol: tcp
    state: absent
    enabled: yes

- name: Firewall rule to allow WinRM HTTP on TCP 5985
  win_firewall_rule:
    name: WinRM HTTP
    localport: 5985
    action: allow
    direction: in
    protocol: tcp
    state: absent
    enabled: yes

- name: Firewall rule to allow WinRM HTTPS on TCP 5986
  win_firewall_rule:
    name: WinRM HTTPS
    localport: 5986
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Firewall rule to allow RDP on TCP port 3389
  win_firewall_rule:
    name: Remote Desktop
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    profiles: private
    state: absent
    enabled: yes

- name: Firewall rule to allow ICMP v4 (ping)
  win_firewall_rule:
    name: ICMP Allow incoming V4 echo request
    enabled: yes
    state: present
    profiles: private
    action: allow
    direction: in
    protocol: icmpv4


- name: Disable Domain firewall
  win_firewall:
    state: disabled
    profiles:
      - Domain
  tags: disable_firewall

