---
- name: Create network interface card
  azure_rm_networkinterface:
    name: "{{ vnic_name }}"
    resource_group: "{{ rg_name }}"
    virtual_network_name: "{{ vnet_name }}"
    subnet_name: subnet01
    security_group_name: "{{ nsg_name }}"
    public_ip: no 
    state: present 
  register: network_interface 

- name: Show private ip
  debug:
    msg: "{{network_interface.ip_configuration.private_ip_address}}"

- name: Create a VM with managed disk
  azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    name: "{{ vm-managed-disk }}"
    admin_username: adminUser
    availability_set: avs-managed-disk
    managed_disk_type: Standard_LRS
    storage_account: "{{ storage_account }}"
    ssh_public_key: "{{ ssh_public_key_vault }}"
    image:
      offer: CoreOS
      publisher: CoreOS
      sku: Stable
      version: latest
    vm_size: "{{ az_vm_size }}"

- name: provision new Azure virtual host
  azure_rm_virtualmachine:
      admin_username: '{{ vm_user }}'
      admin_password: "{{ vm_password }}"
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      name: "{{ vm_name }}"
      resource_group: "{{ resource_group }}"
      state: present
      vm_size: Standard_D1
      storage_account_name: "{{ vm_name }}"
      virtual_network_name: "{{ vm_name }}"
      subnet_name: "{{ vm_name }}"

- name: create Azure vm extension to enable HTTPS WinRM listener
  azure_rm_virtualmachine_extension:
      name: winrm-extension
      resource_group: "{{ resource_group }}"
      virtual_machine_name: "{{ vm_name }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
      auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  wait_for:
    port: 5986
    host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
    timeout: 600