---
- name: Create file with multiple attributes
  win_dsc:
    resource_name: File
    DestinationPath: C:\ansible\dsc
    Ensure: Present
    Type: Directory

- name: Ensure SMB1 is not deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: FS-SMB1
    Ensure: Absent

- name: Ensure FTP is not deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: Web-Ftp-Server
    Ensure: Absent

- name: Delete IIS Default Website
  win_dsc:
    resource_name: xWebsite
    Ensure: Absent
    Name: Default Web Site

- name: Create IIS Website with Binding and Authentication options
  win_dsc:
    resource_name: xWebsite
    Ensure: Present
    Name: DSC Website
    State: Started
    PhysicalPath: C:\inetpub\wwwroot
    BindingInfo: # Example of a CimInstance[] DSC parameter (list of dicts)
    - Protocol: http
      Port: 80
      IPAddress: '*'
    AuthenticationInfo: # Example of a CimInstance DSC parameter (dict)
      Anonymous: no
      Basic: true
      Digest: false
      Windows: yes

- name: Install Git
  win_dsc:
    resource_name: cChoco
    Name: 'Git'
    Ensure: 'Present'
    DependsOn: '[cChocoInstaller]installChoco'  