---
- name: Install PS Modules
  win_psmodule:
    name: '{{ item }}'
    state: present
  with_items:
  - xWebAdministration
  - CISDSC
  - cChoco

- name: cChoco cChocoInstaller
  win_dsc:
    resource_name: cChocoInstaller
    InstallDir: 'C:\choco'

- name: Create file with multiple attributes
  win_dsc:
    resource_name: File
    DestinationPath: C:\ansible\dsc
    Ensure: Present
    Type: Directory

- name: Install Windows Feature Set
  win_dsc:
    resource_name: WindowsFeature
    Name: "{{ item }}"
    Ensure: Present
  with_items:
    - 'Web-Server'
    - 'DNS'
    - 'RSAT-DNS-Server'

- name: Remove Feature Sets
  win_dsc:
    resource_name: WindowsFeature
    Name: "{{ item }}"
    Ensure: Absent
  with_items:
    - 'FS-SMB1'
    - 'Web-Ftp-Server'

- name: Delete IIS Default Website
  win_dsc:
    resource_name: xWebSite
    Ensure: Absent
    Name: Default Web Site

- name: Create IIS Website with Binding and Authentication options
  win_dsc:
    resource_name: xWebsite
    Ensure: Present
    Name: DSC Website
    State: Started
    PhysicalPath: C:\inetpub\wwwroot
    BindingInfo: # Example of a CimInstance[] DSC parameter (list of dicts)
    - Protocol: http
      Port: 80
      IPAddress: '*'
    AuthenticationInfo: # Example of a CimInstance DSC parameter (dict)
      Anonymous: no
      Basic: true
      Digest: false
      Windows: yes

- name: Firewall rule to allow WinRM HTTPS on TCP 5986
  win_firewall_rule:
    name: WinRM HTTPS
    localport: 5986
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Install Software
  win_dsc:
    resource_name: cChocoPackageInstaller
    Name: '{{ item }}'
    Ensure: 'Present'
    DependsOn: '[cChocoInstaller]installChoco'
  with_items:
    - 'Git'
    - 'notepadplusplus'
    - 'microsoft-edge'
    - 'sysinternals'
    - 'chocolatey-core.extension'
    - 'vscode'
    - 'vscode-python'
    - 'vscode-python-test-adaptor'
    - 'vscode-pylance'
    - 'vscode-intellicode'
    - 'vscode-ansible'
    - 'microsoft-windows-terminal'
    #- '1password'
    - 'op'
    - 'Atom'
    - 'python3'
    - 'pip'
    - 'winget'