---
- name: cChoco cChocoInstaller
  win_dsc:
    resource_name: cChocoInstaller
    InstallDir: 'C:\choco'

- name: Create file with multiple attributes
  win_dsc:
    resource_name: File
    DestinationPath: C:\ansible\dsc
    Ensure: Present
    Type: Directory

- name: Ensure SMB1 is not deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: FS-SMB1
    Ensure: Absent

- name: Ensure FTP is not deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: Web-Ftp-Server
    Ensure: Absent

- name: Delete IIS Default Website
  win_dsc:
    resource_name: xWebsite
    Ensure: Absent
    Name: Default Web Site

- name: Create IIS Website with Binding and Authentication options
  win_dsc:
    resource_name: xWebsite
    Ensure: Present
    Name: DSC Website
    State: Started
    PhysicalPath: C:\inetpub\wwwroot
    BindingInfo: # Example of a CimInstance[] DSC parameter (list of dicts)
    - Protocol: http
      Port: 80
      IPAddress: '*'
    AuthenticationInfo: # Example of a CimInstance DSC parameter (dict)
      Anonymous: no
      Basic: true
      Digest: false
      Windows: yes

- name: "Install {{ item }} Software"
  win_dsc:
    resource_name: cChocoPackageInstaller
    Name: '{{ item }}'
    Ensure: 'Present'
    DependsOn: '[cChocoInstaller]installChoco'
  with_items:
    - 'Git'
    - 'notepadplusplus'
    - 'microsoft-edge'
    # - 'sysinternals'
    # - 'chocolatey-core.extension'
    # - 'vscode'
    # - 'vscode-python'
    # - 'vscode-python-test-adaptor'
    # - 'vscode-pylance'
    # - 'vscode-intellicode'
    # - 'microsoft-windows-terminal'
    # - '1password'
    # - 'op'
    # - 'Atom'
    # - 'python3'
    # - 'pip'

# - name: Install Git
#   win_dsc:
#     resource_name: cChocoPackageInstaller
#     Name: 'Git'
#     Ensure: 'Present'
#     DependsOn: '[cChocoInstaller]installChoco'  

# - name: Install Notepad++
#   win_dsc:
#     resource_name: cChocoPackageInstaller
#     Name: 'notepadplusplus'
#     Ensure: 'Present'
#     DependsOn: '[cChocoInstaller]installChoco'

# - name: Install Microsoft Edge
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'microsoft-edge'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install Sysinternals
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'sysinternals'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install Choco extensions
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'chocolatey-core.extension'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install VSCode
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'vscode'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install VSCode Python3 extensions
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'vscode-python'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install VSCode Python Test Adaptor
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'vscode-python-test-adaptor'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install VSCode Pylance
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'vscode-pylance'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install VSCode Intellicode
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'vscode-intellicode'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install Windows Terminal
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'microsoft-windows-terminal'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install 1Password
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: '1password'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install 1Password CLI
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'op'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install Atom
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'atom'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install Python3
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'python3'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'

# - name: Install 'pip'
#   win_dsc:
#       resource_name: cChocoPackageInstaller
#       Name: 'pip'
#       Ensure: 'Present'
#       DependsOn: '[cChocoInstaller]installChoco'