---
- name: Install PS Modules
  win_psmodule:
    name: '{{ item }}'
    state: Present
  with_items:
  - xWebAdministration
  - xWebsite
  - CISDSC
  - cChoco

- name: cChoco cChocoInstaller
  win_dsc:
    resource_name: cChocoInstaller
    InstallDir: 'C:\choco'

- name: Create file with multiple attributes
  win_dsc:
    resource_name: File
    DestinationPath: C:\ansible\dsc
    Ensure: Present
    Type: Directory

- name: Ensure SMB1 is not deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: FS-SMB1
    Ensure: Absent

- name: Ensure FTP is not deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: Web-Ftp-Server
    Ensure: Absent

- name: Delete IIS Default Website
  win_dsc:
    resource_name: xWebsite
    Ensure: Absent
    Name: Default Web Site
    
#- name: Ensure DNS is installed
#  win_dsc:
#    resource_name: WindowsFeature
#    Name: DNS
#    Ensure: Present#
#
#- name: Ensure RSAT DNS Tools are installed
#  win_dsc:
#    resource_name: WindowsFeature
#    Name: RSAT-DNS-Server
#    Ensure: Present

#- name: Create IIS Website with Binding and Authentication options
#  win_dsc:
#    resource_name: xWebsite
#    Ensure: Present
#    Name: DSC Website
#    State: Started
#    PhysicalPath: C:\inetpub\wwwroot
#    BindingInfo: # Example of a CimInstance[] DSC parameter (list of dicts)
#    - Protocol: http
#      Port: 80
#      IPAddress: '*'
#    AuthenticationInfo: # Example of a CimInstance DSC parameter (dict)
#      Anonymous: no
#      Basic: true
#      Digest: false
#      Windows: yes

- name: Install Software
  win_dsc:
    resource_name: cChocoPackageInstaller
    Name: '{{ item }}'
    Ensure: 'Present'
    DependsOn: '[cChocoInstaller]installChoco'
  with_items:
    - 'Git'
    - 'notepadplusplus'
    - 'microsoft-edge'
    - 'sysinternals'
    - 'chocolatey-core.extension'
    - 'vscode'
    - 'vscode-python'
    - 'vscode-python-test-adaptor'
    - 'vscode-pylance'
    - 'vscode-intellicode'
    - 'vscode-ansible'
    - 'microsoft-windows-terminal'
    #- '1password'
    - 'op'
    - 'Atom'
    - 'python3'
    - 'pip'
    - 'winget'