---
- name: Create file with multiple attributes
  win_dsc:
    resource_name: File
    DestinationPath: C:\ansible\dsc
    Ensure: Present
    Type: Directory

- name: ENSURE SMB1 is not Deployed
  win_dsc:
    resource_name: WindowsFeature
    Name: SMB1
    Ensure: Absent