---
- name: Create a managed Azure Container Services (AKS) instance
  azure_rm_aks:
    name: myAKS
    location: "{{ location }}"
    resource_group: "{{ rg_name }}"
    dns_prefix: akstest
    kubernetes_version: 1.14.6
    linux_profile:
      admin_username: azureuser
      ssh_key: "{{ ssh_public_key_vault }}"
    service_principal:
      client_id: "{{ key_vault_client_id }}"
      client_secret: "{{ client_secret_key_vault }}"
    agent_pool_profiles:
      - name: default
        count: 5
        vm_size: Standard_D2_v2
    tags:
      Environment: Production