---
- name: Create Foundational Azure BlueShift Resource Creation
  hosts: localhost
  connection: local
  # Below is UTF-16 Base64 encoding for:
    #   Invoke-Expression -Command ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1')); Enable-WSManCredSSP -Role Server -Force
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=
   
  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - include: Common/tasks/main.yml
      tags: [Common, all]

    - include: ResourceGroup/tasks/main.yml
      tags: [CreateRG, all]

    - include: VirtualNetwork/tasks/main.yml
      tags: [CreateVnet, all]

    - include: Subnets/tasks/main.yml
      tags: [CreateSubnets, all]

    - include: NSG/tasks/main.yml
      tags: [CreateNSG, all]

    - include: StorageAccount/tasks/main.yml
      tags: [CreateStorageAccount, all]

    - include: IaaS/tasks/main.yml
      tags: [CreateIaaS, all]

    - include: PaaS/tasks/main.yml
      tags: [CreatePaaS, all]

    - include: Services/tasks/main.yml
      tags: [CreateServices, all]

    - include: Application/tasks/main.yml
      tags: [CreateApplication, all]

    - include: Closeout/tasks/main.yml
      tags: [Closeout, all]
  
  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."