---

- name: Set system facts based on gather facts module
  block:
      - name: Set fact is system is standalone
        set_fact:
            win2019cis_is_standalone: true
        when:
            - ansible_windows_domain_role ==  'Stand-alone server'

      - name: Set fact if domain controller role
        set_fact:
            win2019cis_is_domain_controller: true
        when:
            - ansible_windows_domain_role | regex_search('(domain controller)')

      - name: set fact if domain member server
        set_fact:
            win2019cis_is_domain_member: true
        when:
            - ansible_windows_domain_role == 'Member server'

- name: Get Windows installation type
  win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
      name: InstallationType
  register: get_windows_installation_type

- name: Set Windows installation type
  set_fact:
      windows_installation_type: "{{ get_windows_installation_type.value | default('') }}"
