---
# tasks file for azure-foundations
# Create Resource Group
# Create or use existing vNet
- name: Create a virtual network
  azure_rm_virtualnetwork:
    resource_group: myResourceGroup
    name: myVirtualNetwork
    address_prefixes_cidr:
        - "10.1.0.0/16"
        - "172.100.0.0/16"
    dns_servers:
        - "127.0.0.1"
        - "127.0.0.2"
    tags:
        testing: testing
        delete: on-exit
# Create 4 subnets with NSG names
- name: Create a subnet
  azure_rm_subnet:
    resource_group: myResourceGroup
    virtual_network_name: myVirtualNetwork
    name: mySubnet
    address_prefix_cidr: "10.1.0.0/24"
# Create Gateways and transit devices
# Create Storage account and private endpoint assignment
- name: create an account
  azure_rm_storageaccount:
    resource_group: myResourceGroup
    name: clh0002
    type: Standard_RAGRS
    tags:
      testing: testing
      delete: on-exit
# Create service inside of subnet