---
- name: Create Active Directory User
  community.windows.win_domain_user:
    name: "{{ username }}"
    firstname: "{{ first_name }}"
    surname: "{{ last_name }}"
    company: BSC
    password: "{{ password }}"
    state: present
    groups:
      - Domain Users
    street: "{{ street_address }}"
    city: "{{ city }}"
    state_province: "{{ state }}"
    postal_code: "{{ zip_code }}"
    country: US
    attributes:
      telephoneNumber: "{{ phone_number }}"
  tags: CreateUser

- name: Delete AD User
  community.windows.win_domain_user:
    name: "{{ username }}"
    firstname: "{{ first_name }}"
    surname: "{{ last_name }}"
    state: absent
  tags: DeleteUser

- name: Ensure the group exists using sAMAccountName
  community.windows.win_domain_group:
    name: "{{ group_name }}"
    scope: global
    path: CN=Builtin,DC=brainstormes,DC=org
    state: present
  tags: CreateGroup

- name: Delete a group using sAMAccountName
  community.windows.win_domain_group:
    name: "{{ group_name }}"
    scope: global
    path: CN=Builtin,DC=brainstormes,DC=org
    state: absent
  tags: DeleteGroup

- name: Add a domain user/group to a domain group
  community.windows.win_domain_group_membership:
    name: "{{ group_name }}"
    members:
      - "{{ username }}"
    state: present
  tags: AddUserToGroup

- name: Remove a domain user from a domain group
  community.windows.win_domain_group_membership:
    name: "{{ group_name }}"
    members:
      - "{{ username }}"
    state: absent
  tags: RemoveUserFromGroup

- name: Get all properties for the specified account using its DistinguishedName
  community.windows.win_domain_object_info:
    identity: "CN={{ username }},CN=Users,DC=brainstormes,DC=org"
    properties: '*'
  register: user_output
  tags: GetUserProperties

- name: Print out Active Directory User Info
  ansible.builtin.debug:
    msg: "{{ user_output }}"
  tags: GetUserProperties

- name: Get all properties for the specified account using its DistinguishedName
  community.windows.win_domain_object_info:
    identity: "CN={{ group_name }},CN=Builtin,DC=brainstormes,DC=org"
    properties: '*'
  register: group_output
  tags: GetGroupProperties

- name: Print out Active Directory Group Info
  ansible.builtin.debug:
    msg: "{{ group_output }}"
  tags: GetGroupProperties

- name: Add or Delete Azure AD Groups
  azure.azcollection.azure_rm_adgroup:
    tenant: "{{ aad_tenant_id }}"
    display_name: "{{ aad_group_name }}"
    mail_nickname: "{{ aad_mail_group_nickname }}"
    state: "{{ aad_action }}"
  tags: ManageAADGroup

- name: Add or Delete Azure AD User
  azure.azcollection.azure_rm_aduser:
    user_principal_name: "{{ username }}"
    tenant: "{{ tenant_id }}"
    state: "{{ aad_action }}"
    account_enabled: "True"
    display_name: "{{ username }}"
    password_profile: "password"
    mail_nickname: "{{ aad_mail_nickname }}"
    given_name: "{{ first_name }}"
    surname: "{{ last_name }}"
    user_type: "Member"
    usage_location: "US"
    mail: "{{ username }}@stormesfamily.org"
  tags: ManageAADUser

- name: Get Azure AD User Info
  azure.azcollection.azure_rm_aduser_info:
    user_principal_name: "{{ username }}@stormesfamily.org"
    tenant: "{{ tenant_id }}"
  register: username_object
  tags: [MoveAADUserToGroup, MoveAADUserFromGroup, TestUserObjectName]

- name: Print out Info
  ansible.builtin.debug:
    msg: "{{ username_object['ad_users'][0].object_id }}"
  tags: TestUserObjectName

- name: Ensure a User is a Member of a Group using display_name and mail_nickname
  azure.azcollection.azure_rm_adgroup:
    tenant: "{{ tenant_id }}"
    display_name: "{{ aad_group_name }}"
    mail_nickname: "{{ aad_mail_group_nickname }}"
    state: 'present'
    present_members:
      - "https://graph.windows.net/{{ tenant_id }}/directoryObjects/{{ username_object['ad_users'][0].object_id }}"
  tags: MoveAADUserToGroup

- name: Ensure a User is not a Member of a Group using display_name and mail_nickname
  azure.azcollection.azure_rm_adgroup:
    tenant: "{{ tenant_id }}"
    display_name: "{{ aad_group_name }}"
    mail_nickname: "{{ aad_mail_group_nickname }}"
    state: 'present'
    absent_members:
      - "{{ username_object['ad_users'][0].object_id }}"
  tags: MoveAADUserFromGroup