---
- name: Create Foundational Azure Resource Group
  hosts: localhost
  connection: local

  pre_tasks:
    - debug:
        msg: "Executing Pre Tasks"

  roles:
    #- Common
    - ResourceGroup
    - VirtualNetwork
    - Subnets
    - NSG
    - StorageAccount
    #- IaaS
    #- PaaS
    #- Services
    #- Application

  post_tasks:
    - debug:
        msg: "Executing Post Tasks"