---
- name: Create Full Foundational Azure BlueShift Resource Group
  hosts: localhost
  connection: local

  roles:
      - Common
      - ResourceGroup
      - VirtualNetwork
      - Subnets
      - NSG
      - StorageAccount
      #- IaaS
      #- PaaS
      - Services
      - Application
      - Closeout