---
- name: Manage Ansible Windows Modules BlueShift Resource Creation
  hosts: all
  gather_facts: yes
   
  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - include_tasks: Common/tasks/main.yml
      tags: Common
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [CreateUser, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [CreateGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [DeleteUser, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [DeleteGroup, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [AddUserToGroup, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [RemoveUserFromGroup, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [GetUserProperties, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [GetGroupProperties, all]
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [ManageAADGroup, all]

  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."