---
- name: Manage Windows Server, Active Directory and Azure AD
  hosts: all
  gather_facts: yes

  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - include_tasks: Common/tasks/main.yml
      tags: Common

    - include_tasks: ADIAM/tasks/main.yml
      tags: [CreateUser, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [CreateGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [DeleteUser, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [DeleteGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [AddUserToGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [RemoveUserFromGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [GetUserProperties, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [GetGroupProperties, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [ManageAADGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [ManageAADUser, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [TestUserObjectName, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [MoveAADUserToGroup, all]

    - include_tasks: ADIAM/tasks/main.yml
      tags: [MoveAADUserFromGroup, all]
    
    - include_tasks: WinModule/tasks/main.yml
      tags: [RebootServer, all]
    
    - import_tasks: WinModule/tasks/main.yml
      tags: [CreateZone, all]
    
    - include_tasks: Services/tasks/main.yml
      tags: [CreateARecord, all]
    
    - name: Importing WinDSC Role
      import_role: 
        name: WinDSC
      tags: [WinDSC, all]

    - name: Importing WinModule Role
      import_role: 
        name: WinModule
      tags: [WinModule, all]
    
    - name: Importing ADIAM Role
      import_role:
        name: ADIAM
      tags: [ADIAM, all]

  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."
