---
- name: Manage Ansible Windows Modules BlueShift Resource Creation
  hosts: all
  gather_facts: yes
   
  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - include_tasks: Common/tasks/main.yml
      tags: Common
    
    - include_tasks: ADIAM/tasks/main.yml
      tags: [CreateUser, CreateGroup, DeleteUser]
  
  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."