---
- name: Manage Ansible Windows Modules BlueShift Resource Creation
  hosts: all
  gather_facts: yes
   
  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - import_role: Common/tasks/main.yml
      tags: Common
    
    - import_role: ADIAM/tasks/main.yml
      tags: [CreateUser, all]
    
    - import_role: ADIAM/tasks/main.yml
      tags: [CreateGroup, all]

    - import_role: ADIAM/tasks/main.yml
      tags: [DeleteUser, all]

  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."