---
- name: Manage Ansible Windows Modules BlueShift Resource Creation
  hosts: all
  gather_facts: true
   
  pre_tasks:
    - debug:
        msg: "Pre Tasks for Orchestration"

  tasks:
    - include: Common/tasks/main.yml
      tags: [Common, all]
    
    - include: ADIAM/tasks/main.yml
      tags: [CreateUser, all]
    
    - include: ADIAM/tasks/delete.yml
      tags: [DeleteUser, all]
  
  post_tasks:
    - debug:
        msg: "Post Tasks for Orchestration."