---
- name: Create a storage account
  azure_rm_storageaccount:
     resource_group: "{{ rg_name }}"
     name: "{{ storage_account_name }}"
     type: Standard_RAGRS 
     location: "{{ region }}"

- name: "SHELL CMD: Create Storage Account"
  ansible.builtin.shell: | 
      az storage account create \
      --name {{ storage_account_name }} \
      --resource-group {{ resource_group }} \
      --location {{ location }} \
      --sku Standard_LRS \
      --public-network-access Disabled
  delegate_to: localhost  
